import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";
import { GeoSearchDataProvider } from "./context/GeoSearchDataProvider";
import {ErrorBoundary} from "react-error-boundary";
import {ErrorPage} from "@/app/components/ErrorPage";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <GeoSearchDataProvider>
          <html lang="en">
          <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
          <ErrorBoundary FallbackComponent={ErrorPage}>
              <Header/>
              {children}
          </ErrorBoundary>
          </body>
          </html>
      </GeoSearchDataProvider>
  );
}
